### ISSUE TITLE
能否设置修改或切换朗读服务商？感觉讯飞有声的智能朗读比百度的听着好听

### ISSUE THREAD

**Issue by zn353010922** [gedoor/legado#295]

**Comment by gedoor** [comment]
阅读用的都是免费的,你说的那个应该是收费的

**Comment by h11128** [comment]
讯飞语记是免费的app，有的读书app可以调用

**Comment by Celeter** [comment]
> 讯飞语记是免费的app，有的读书app可以调用

app是免费的，不代表直接用他的接口是免费的

**Comment by h11128** [comment]
可以在讯飞语记里面直接设置全局接口，这样就能改变阅读app里面的发音人。这是免费的我试过了




    


在2020年08月10日 23:09，Celeter 写道： 

讯飞语记是免费的app，有的读书app可以调用

app是免费的，不代表直接用他的接口是免费的

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gedoor/legado/issues/295#issuecomment-671698195",
"url": "https://github.com/gedoor/legado/issues/295#issuecomment-671698195",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
